package datastore

import "time"

type UserArtistTag struct {
	ID int

	UserID   int
	ArtistID int

	TagName string
	// FavoriteShorterm とか
}

type Track struct {
	ID int
}

type ArtistTrackTag struct {
	ID int

	ArtistID int
	TrackID  int

	TagName string
}

type UserTrackTag struct {
	ID int

	UserID  int
	TrackID int

	TagName string
}

type AutoGenerated []struct {
	Track struct {
		Artists []struct {
			Name         string `json:"name"`
			ID           string `json:"id"`
			URI          string `json:"uri"`
			Href         string `json:"href"`
			ExternalUrls struct {
				Spotify string `json:"spotify"`
			} `json:"external_urls"`
		} `json:"artists"`
		AvailableMarkets []string `json:"available_markets"`
		DiscNumber       int      `json:"disc_number"`
		DurationMs       int      `json:"duration_ms"`
		Explicit         bool     `json:"explicit"`
		ExternalUrls     struct {
			Spotify string `json:"spotify"`
		} `json:"external_urls"`
		Href        string `json:"href"`
		ID          string `json:"id"`
		Name        string `json:"name"`
		PreviewURL  string `json:"preview_url"`
		TrackNumber int    `json:"track_number"`
		URI         string `json:"uri"`
	} `json:"track"`
	PlayedAt time.Time `json:"played_at"`
	Context  struct {
		ExternalUrls struct {
			Spotify string `json:"spotify"`
		} `json:"external_urls"`
		Href string `json:"href"`
		Type string `json:"type"`
		URI  string `json:"uri"`
	} `json:"context"`
}
